{% set version = "1.0.0" %}

package:
  name: pygls
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pygls/pygls-{{ version }}.tar.gz
  sha256: c2a1c22e30028f7ca9d3f0a04da8eef29f0f1701bdbd97d8614d8e1e6711f336

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=44
    - setuptools-scm >=3.4.3
    - toml
  run:
    - python >=3.7
    - lsprotocol
    - typeguard >=2.10.0,<3

test:
  source_files:
    - tests
  requires:
    - m2-grep  # [win]
    - mock
    - pip
    - pytest
    - pytest-asyncio
    - pytest-cov
  imports:
    - pygls
  commands:
    - pip check
    - pip list
    - pip list | grep -iE 'pygls\s+{{ version.replace("\\", "\\\\") }}$'
    - pytest tests -vv --cov=pygls --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=82

about:
  home: https://pygls.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - ThirdPartyNotices.txt
  summary: a pythonic generic language server (pronounced like "pie glass").
  description: |
    pygls (pronounced like "pie glass") is a pythonic generic implementation of
    the Language Server Protocol for use as a foundation for writing language
    servers using Python (e.g. Python, XML, etc.). It allows you to write your
    own language server in just a few lines of code.
  dev_url: https://github.com/openlawlibrary/pygls
  doc_url: https://pygls.readthedocs.io
  doc_source_url: https://github.com/openlawlibrary/pygls/tree/master/docs/source

extra:
  recipe-maintainers:
    - bollwyvl
